### ISSUE TITLE
ItemJoin - World-Change not working (No Error)

### ISSUE THREAD

**Issue by R4zzer** [RockinChaos/ItemJoin#106]
Hello, i want to configure and test the plugin. I noticed that, the World-Change is not working. I get the Items for 1-20 Milliseconds and then are they again gone.

PS: The Command for the Item via /itemjoin get <id> is working.

```
Plugins:
FirstJoinPlus, ChestCommands, Multiverse-Core, Multiverse-Inventories, PlaceholderAPI
```

```
Items.yml:

Global-Settings:
  Prevention:
    prevent-pickups: false 
    AllowOPBypass: false
    CreativeBypass: false
  Clear-On:
    clear-on-join: false
    clear-on-world-change: false
    clear-only-itemjoin-on-join: true
    clear-only-itemjoin-on-world-change: true
    AllowOPBypass: false
  First-Join:
    FirstJoin-Mode-Enabled: false
  Get-Items:
    ItemJoin-Specific-Items: true
    Global-Items: false
    Delay: 2

world-list:
  - WorldX
  - WorldX_Spawn
  - Spawn

WorldX:
  items:
    survival:
      id: 387
      slot: 4
      name: '&e➤ &b&lSurvival Guide'
      author: '&c&l&oPlayInfected'
      lore:
      - '&7Rechtsklicke dieses Item, damit wir diese'
      - '&7grauenvolle Welt erklären können.'
      pages:
        - 'newpage: &bYou can get this book on join!'
        - 'newline: &aThis book also supports &ccolor codes!'
        - 'newline: &0'
        - 'newline: &cHow do custom books work?'
        - 'newline: &0'
        - 'newline: &0You can set an &cauthor&0'
        - 'newline: &0as shown in the items.yml'
        - 'newline: &0I set it to &bItemJoin.'
        - 'newline: &0'
        - 'newpage: &cHow do you create a new page?'
        - 'newline: &0'
        - 'newline: &0As displayed to the left in the items.yml'
        - 'newline: &0Use &bnewpage&0 and &cnewline&0 to create your pages.'
        - 'newline: &cnewpage &0will start the next page.'
        - 'newline: &cnewline &0will create a new line for that page.'
        - 'newpage: &bItemJoin &0by RockinChaos!'
        - ':endthebook:'
      itemflags:
        - 'self-drops'
        - 'death-drops'
        - 'respawn'
        
Spawn:
  items:
    projectx:
      id: 98
      slot: 0
      name: '&c&l➤ &c&lProjectX &7- &e&lBetreten'
      enchantment:
      - 'FIRE_ASPECT:1'
      commands:
        - 'warp ProjectX_2'
      commands-cooldown: 5
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK
      cooldown-message: '&c&lPlayInfected-Bungee [&bPI&c] &7| Bitte warte noch &e%timeleft% &7Sekunden!'
      itemflags:
        - 'inventory-modify'
        - 'cancel-events'
        - 'self-drops'
        - 'death-drops'
    thelab:
      id: 373
      slot: 1
      name: '&c&l➤ &3&lThe&b&lLab &7- &e&lBetreten'
      commands:
        - 'tl join 1'
      commands-cooldown: 5
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK
      cooldown-message: '&c&lPlayInfected-Bungee [&bPI&c] &7| Bitte warte noch &e%timeleft% &7Sekunden!'
      itemflags:
        - 'inventory-modify'
        - 'cancel-events'
        - 'self-drops'
        - 'death-drops'
        - 'respawn'
        
WorldX_Spawn:
  items:
    lobby:
      id: 345
      slot: 8
      name: '&c&l➤ &e&lZurück zur Lobby'
      commands:
        - 'server: LOBBYSERVER'
      commands-cooldown: 5
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK
      cooldown-message: '&c&lPlayInfected-Bungee [&bPI&c] &7| Bitte warte noch &e%timeleft% &7Sekunden!'
      itemflags:
        - 'inventory-modify'
        - 'cancel-events'
        - 'self-drops'
        - 'death-drops'
```
