### ISSUE TITLE
Book requires extra newpage

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#154]
Spigot 1.12.2 latest
ItemJoin 4.6

Book item requires an extra _newpage_, so that the real last page appears.
```
items:
  world-book:
    id: WRITTEN_BOOK
    slot: 8
    count: 1
    name: '&4World Book'
    author: 'rambeau'
    lore:
      - '&7Introduction to worlds'
    pages:
      - 'newpage: &lGeneral'
      - 'newline: &0'
      - 'newline: BlackDog is a friendly MineCraft environment. Explore, build, share, and enjoy. Griefing is not allowed. PvP is allowed. Dogs are black in most worlds.'
      - 'newline: &0'
      - 'newline: Right-click the clock in inventory slot 9 to move among worlds.'
      - 'newpage: &4&lThe Playground&0 is an &leasy creative&0 world. It is a good place to begin. Find a place to build, and experiment with MineCraft. The creative environment gives you access to everything you need. Dogs in this world are black.'
      - 'newpage: &4&lThe Arcade&0 is a world of &lgames&0. Try bumper cars, snake, minesweeper, and others. Not all games are active, but can be made so on request.'
      - 'newpage: &4&lLuckyBlock&0 is a world of &llucky blocks&0. You can obtain random prizes (not all good ones), and fight battles with whatever you find. &lLasers&0 are available.'
      - 'newpage: &4&lSkyBlock&0 is a world of &lsky islands&0. Try to survive with very limited resource, and use your ingenuity to build them into a thriving environment.'
      - 'newpage: &4&lSupreme&0 is a &lparkour&0 world. Test your maneuvering and jumping skills. You will die many times as you attempt to complete the course.'
      - 'newpage: &4&lBlackDog&0 is a more &ldifficult survival&0 world. Monsters spawn at night (and in the shadows), so you have to find shelter, food, tools and weapons to stay alive. Go it alone, or join forces with others in a faction.'
      - 'newpage: &4&lWhiteDog&0 is another &ldifficult survival&0 world. It is based on a private map, with high snowy mountains and snowy plains. Look for polar bears. Factions work across all the survival worlds. Dogs in this world are white.'
      - 'newline: &0'
      - 'newline: &l* Restricted world'
      - 'newpage: &4&lTheCity&0 is another &lsurvival&0 world. It is based on a private map, full of buildings, streets, and parks. There is plenty to explore, and the usual requirements to stay alive.  Dogs in this world are black.'
      - 'newline: &0'
      - 'newline: &l* Restricted world'
      - 'newpage: &4&lYellowDog&0 is an &lextra hard survival&0 world. There is a village near the spawnpoint, so you can gather food, and trade items with the Villagers. Factions work across this world as well. Dogs in this world are yellow.'
      - 'newline: &0'
      - 'newline: &l* Restricted world'
      - 'newpage: Thanks for reading. You can leave the book in the shulker box.'
      - 'newpage: &0'
    itemflags: death-drops, first-join
    triggers: join
    permission-node: 'commandsign.execute.41'
    enabled-worlds: world_lobby
```
Note final _newpage_. The page
```
Thanks for reading. You can leave the book in the shulker box.
```
does not appear without the final _newpage_.
