### ISSUE TITLE
Item does not appear with expected permission

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#162]
Spigot 1.12.2
ItemJoin 4.7
DeluxeMenus 1.10.2
Multiverse-* 2.6.0-b734

On first join, player is spawned in world_lobby, and should have two IJ-created inventory items (0-indexed):
- slot 7: book
- slot 8: watch (clock)
![untitled](https://user-images.githubusercontent.com/17748923/35127549-773c8ab0-fc67-11e7-85ec-9b60165a9b53.png)

What does happen: only the book in slot 7
- slot 7: book
![untitled](https://user-images.githubusercontent.com/17748923/35127629-d9e24cc2-fc67-11e7-9b28-92f98e85210b.png)

Player can then leave world_lobby through portals to other worlds. In any of those worlds, the slot-8 item is created. When player returns to world_lobby, the slot-8 item is created.

I must be doing something wrong, but I don't see what.

```
#// <>==<>==<> ItemJoin's Custom Items On Join, by RockinChaos <>==<>==<> //#
#// See the Documentations page for a more in-depth tutorial; https://www.spigotmc.org/wiki/itemjoin/ //#
items-Version: 6
items-Delay: 2
items-Overwrite: true
items-Spamming: false

items:
  world-book:
    id: WRITTEN_BOOK
    slot: 7
    count: 1
    name: '&4BlackDog'
    author: 'rambeau'
    lore:
      - '&7rules and worlds'
    pages:
      - 'newpage: &lGeneral'
      - 'newline: &0'
      #
      # book content elided...
      #
      - 'newline: &0'
      - 'newline: You can leave the book in the shulker box.'
      - ':endthebook:'
    itemflags: death-drops, first-join
    triggers: join
    permission-node: 'commandsign.execute.41'
    enabled-worlds: world_lobby

  changeWorld-item:
    id: WATCH
    data-value: 0
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    enchantment: FIRE_ASPECT:1
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    # disabled-worlds-UNSUPPORTED: world_void
    enabled-worlds: world, world_lobby, world_blackdog, world_blackdog_nether, world_blackdog_the_end, world_city, world_city_nether, world_city_the_end, world_luckyblock, world_minigames, world_nether, world_skyblock, world_skyblock_nether, world_skyblock_the_end, world_supreme, world_the_end, world_whitedog, world_whitedog_nether, world_whitedog_the_end, world_yellowdog, world_yellowdog_nether, world_yellowdog_the_end
```
