### ISSUE TITLE
Item click-through

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#163]
Spigot 1.12.2 latest
ItemJoin 4.7
CommandSigns 1.5.5

```
  changeWorld-item:
    id: WATCH
    data-value: 0
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    enchantment: FIRE_ASPECT:1
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    enabled-worlds: list-of-worlds-which-includes-current-world
```
Due to permissions, DeluxeMenus cannot be opened in the current world. The slot 8 item (WATCH/clock) can be right-clicked through to trigger commands in a sign, despite _cancel-events_ item flag.

**Comment by SlimeDog** [comment]
In another world, where DeluxeMenus is enabled, the slot 8 item can again be right-clicked through to trigger commands in a sign, and DM menu is popped open.

**Comment by RockinChaos** [comment]
Ah wait so you are having an issue where if you hold the item in your hand and click on a sign that the item still executes the commands?

**Comment by SlimeDog** [comment]
Exactly. The item should raise the DeluxeMenus menu (or not, in the first case). But in neither case should the right-click pass through to the sign (as I understand it).

**Comment by RockinChaos** [comment]
So just to be sure so I can test and fix this, you want the ItemJoin item to NOT execute the command if you click on an interactable such as a ServerSign that would execute its own command?

**Comment by SlimeDog** [comment]
Let me be sure that I understand the meaning of
```
itemflags: cancel-events
```
My understanding is that with that flag set, any actions engaged by the IJ item would be canceled. Is that the intent, or is it something else?

**Comment by RockinChaos** [comment]
cancel-events are for any action that isnt ItemJoin.
cancel-events are all events bukkit/Minecraft initiates.

Examples; opening a book, using a firework, eating food, tossing the hook to the fishing pole, etc.

**Comment by SlimeDog** [comment]
I see. So how about right-click on a sign? My memory is that the right-click and the events behind it used to be canceled, but it and they are not, presently.

**Comment by RockinChaos** [comment]
Right-click events on a sign would be canceled but not the command that is executed by ItemJoin as it is not an event.

**Comment by SlimeDog** [comment]
The command is executed as a result of the right-click, by DeluxeMenus. Surely that is an event; the issue is whether it can be trapped and canceled.

**Comment by RockinChaos** [comment]
To double check, which event is suppose to trigger when you right-click the sign?

ItemJoin, or the Sign with the command bound to it?

**Comment by SlimeDog** [comment]
Right-click on a sign triggers a [CommandSigns](https://www.spigotmc.org/resources/command-signs.10512/) sequence (for signs where that is configured; that is the issue here).

Right-click on the IJ item (WATCH=clock) triggers opening a [DeluxeMenus](https://www.spigotmc.org/resources/deluxemenus.11734/) menu.
```
  changeWorld-item:
    id: WATCH
    data-value: 0
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    enchantment: FIRE_ASPECT:1
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
```
The issue occurs when I right-click on the sign with the IJ item in hand.
