### ISSUE TITLE
Item does not open DM menu

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#177]
Spigot 1.13 latest build
ItemJoin 4.9-b131 (latest update)
DeluxeMenus 1.10.5 (no update available, but works with 1.13 - see below)
LuckPerms 4.2.54 (latest 1.13 update)

No errors on start-up. Right-click on CLOCK causes DeluxeMenus to check permissions, but menu does not open; no console/log errors. Menu can be opened explicitly by DeluxeMenus.

config.yml
```
#// <>==<>==<> ItemJoin's Settings, by RockinChaos  <>==<>==<> //#
#// See the Documentations page for a more in-depth tutorial; https://www.spigotmc.org/wiki/itemjoin/ //#
#// For per-world support this best works with Multiverse-Inventories! http://dev.bukkit.org/bukkit-plugins/multiverse-inventories //#
config-Version: 6

 #// English is currently the only support language at the moment! //#
Language: 'English'
CheckForUpdates: false
Log-Coloration: false
Log-Commands: true
Items-Permissions: true
OPItems-Permissions: false
OPCommands-Permissions: false
GetItem-Permissions: false
Debugging-Mode: false


#// Global Settings for ItemJoin. //#
Prevent-Pickups: false
HeldItem-Slot: None
NewNBT-System: true
#// If you change NewNBT-System from true/false, it is recommended to clear all old ItemJoin items. //#

#// Global Clear Items for ItemJoin. //#
#// Set Clear-Items to ItemJoin or to All, ItemJoin clears only the ItemJoin items and All will clear all items. //#
#// If you want one of these functions to only clear specific worlds, replace false with the world names separated by commas.  //#
Clear-Items: ItemJoin
Clear-On-Join: false
Clear-On-WorldChanged: false
AllowOPBypass: false
CreativeBypass: false


#// Global Commands for ItemJoin on join, these commands are executed by console. //#
enabled-global-commands: false
enabled-worlds: world, world_nether
global-commands:
  - 'itemjoin get <item> <player>'
  - 'first-join: say This is a command only executed once per world, per player.'
  
  
#// Itemflag Bypass Permissions //#
InventoryBypass-Permission: false

#// These are optional dependencies, only change these if you are looking to use them in conjunction with ItemJoin, changing the values will require a server restart. //#
Vault: true
PlaceholderAPI: true
Multiverse-Core: true
Multiverse-Inventories: true
PerWorldInventory: false
PerWorldPlugins: false
xInventories: false
TokenEnchant: false
HeadDatabase: false
WorldGuard: true
BetterNick: false
MyWorlds: false
AuthMe: false
```

items.yml
```
#// <>==<>==<> ItemJoin's Custom Items On Join, by RockinChaos <>==<>==<> //#
#// See the Documentations page for a more in-depth tutorial; https://www.spigotmc.org/wiki/itemjoin/ //#
items-Version: 6
items-Delay: 2
items-Overwrite: true
items-Spamming: false
items-RestrictCount : true

  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    enchantment: FIRE_ASPECT:1
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    # disabled-worlds-UNSUPPORTED: world_void
    enabled-worlds: world, world_lobby, world_blackdog, world_blackdog_nether, world_blackdog_the_end, world_city, world_city_nether, world_city_the_end, world_luckyblock, world_minigames
, world_nether, world_skyblock, world_skyblock_nether, world_skyblock_the_end, world_parkour, world_the_end, world_whitedog, world_whitedog_nether, world_whitedog_the_end, world_yellowdog
, world_yellowdog_nether, world_yellowdog_the_end
```
