### ISSUE TITLE
Lore not displayed

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#189]
Spigot 1.13.2 latest
ItemJoin 4.9.1-b155

Custom lore is not displayed with the item in slot 17. Custom lore is displayed if I change the slot to the hotbar (say, slot 7).

```
  identifier-lobby:
    id: BRICKS
    slot: 17
    count: 1
    name: '&bLobby'
    lore:
      - 'world identifier'
      - 'op only'
    permission-node: 'blackdog.op'
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    enabled-worlds: world_lobby
```
No errors on **/itemjoin reload**.
