### ISSUE TITLE
Locked item moved in inventory

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#198]
Spigot 1.13.2
ItemJoin 5.0.2-b193

Locked item moved in inventory, triggered by a random accidental keystroke. I was in creative mode. I have no clue what the keystroke was, and cannot replicate it. I am posting only to record the incident.

config.yml (sans comments)
```
config-Version: 6

Language: 'English' 
CheckForUpdates: false
Log-Coloration: false
Log-Commands: true
Items-Permissions: true
OPItems-Permissions: false
OPCommands-Permissions: false
GetItem-Permissions: false
Debugging-Mode: false
    
Prevent-InventoryModify: false
Prevent-Pickups: false
enabled-prevent-worlds: ALL
HeldItem-Slot: 0
NewNBT-System: true
      
Clear-Items: ItemJoin
Clear-On-Join: false
Clear-On-WorldChanged: false
Protect-SpecialItems: true
AllowOPBypass: false
CreativeBypass: false
      
enabled-global-commands: false
enabled-worlds: world, world_nether
global-commands:
  - 'itemjoin get <item> <player>'
  - 'first-join: say This is a command only executed once per world, per player.'
       
InventoryBypass-Permission: false
      
Multiverse-Core: true
Multiverse-Inventories: true
PlaceholderAPI: true 
Vault: true
WorldGuard: true
      
AuthMe: false
BetterNick: false 
HeadDatabase: false
MyWorlds: false
PerWorldInventory: false
PerWorldPlugins: false 
TokenEnchant: false
xInventories: false
```
items.yml (relevant content)
```
items:
...
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    enchantment: FIRE_ASPECT:1
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    enabled-worlds: world, world_lobby, ...
```
Note: itemflags:inventory-modify
