### ISSUE TITLE
Items not being given when teleporting into region

### ISSUE THREAD

**Issue by ShawnPR1** [RockinChaos/ItemJoin#209]
1.) Version of ItemJoin: ***5.0.3***
2.) Version of Spigot: ***Latest***
3.) Issue:
I have an item set up that needs to be given to players when they enter a spawn region. It works perfectly when you walk into the region, but it does not give the item to the player when they teleport into the region.
4.) Relevant YAML:
```yml
  survival-wings:
    permissions-node: itemjoin.default
    id: elytra
    slot: chestplate
    name: '&cRed&1Bull&7 Gives you Wings'
    lore:
    - ''
    - '&7&oFly you fools!'
    itemflags: inventory-modify
    triggers: region-enter
    enabled-regions: spawn
    enabled-worlds: VikingsDen
```

As stated above, this works perfectly when a player walks into the region, but the item is not received when the player teleports into the region (even if they are in the same world).

This plugin is damn near perfect for anything imaginable I just wanna say that. This is a minor inconvenience, but I thought I may as well post it here since there are no item triggers called *region-teleport*. *region-enter* (I assume) should handle that as well.
