### ISSUE TITLE
Option to cancel / clear all pending command delays if a player dies.

### ISSUE THREAD

**Issue by mibby** [RockinChaos/ItemJoin#212]
I have a special item that players can consume upon entering a world to safely leave it.

```
  Flare_Gun:
    id: WOODEN_HOE
    slot: Arbitrary
    durability: 5
    name: '&6Ordinary Flare Gun'
    lore:
    - '&8&m--------&f&l &nGeneral&8 &m--------'
    - '&cGun'
    - ''
    - '&8&m-------------------------'
    - ''
    - '&7Clicking while holding this will call for extraction.'
    - '&7Please wait 5 minutes for extraction.'
    - ''
    itemflags: death-drops, self-drops, item-store, unbreakable, hide-attributes, disposable
    triggers: world-change, join
    enabled-worlds: darkzone
    commands:
      right-click:
      - 'message: &8[&5DarkZone&8] &bExtraction Inbound...'
      - 'console: bar send %player% Extraction_Inbound... Blue 0 300'
      - 'delay: 6000'
      - 'console: mvtp %player% e:spawn:-935.5,60,-217.5'
      - 'message: &8[&5DarkZone&8] &bYou have been extracted from the darkzone.'
    commands-cooldown: 310
    cooldown-message: '&8[&5DarkZone&8] &bYou have already fired your flare. Please wait for extraction.'
    permission-node: 'itemjoin.darkzone.flare'
```

However if they use the item and then die - being brought back to spawn, the delayed command still ticks down in the background and runs even if they are no longer in the world.

Would it be possible to cancel all pending / delayed commands if the player dies or are no longer in the world?
