### ISSUE TITLE
Option to launch a particle or firework on item use.

### ISSUE THREAD

**Issue by mibby** [RockinChaos/ItemJoin#213]
Would it be possible to add an option to launch a firework or forced directional particle (or even particle effect/style with EffectLib) on use of an item? I have a special flare gun that players can use and consume, but it's a bit bland when nothing occurs upon interaction.

```
  Flare_Gun:
    id: WOODEN_HOE
    slot: Arbitrary
    durability: 5
    name: '&6Ordinary Flare Gun'
    lore:
    - '&8&m--------&f&l &nGeneral&8 &m--------'
    - '&cGun'
    - ''
    - '&8&m-------------------------'
    - ''
    - '&7Click to call for extraction.'
    - '&7Extraction time: 5 minutes'
    - ''
    itemflags: death-drops, self-drops, item-store, unbreakable, hide-attributes, disposable
    triggers: world-change, join
    enabled-worlds: darkzone
    commands:
      right-click:
      - 'console: tellraw @a ["",{"text":"DarkZone","bold":true,"color":"gray"},{"text":" » ","bold":true,"color":"white"},{"text":"Extraction inbound for %player%","color":"gray"}]'
      - 'console: bar send %player% Extraction_Inbound... Blue 0 300'
      - 'delay: 6000'
      - 'console: mvtp %player% e:spawn:-935.5,60,-217.5'
      - 'message: &7&lDarkZone &f&l» &7You have been safely extracted from the darkzone.'
    commands-cooldown: 310
    cooldown-message: '&7&lDarkZone &f&l» &7You have already fired your flare. Please wait for extraction.'
    permission-node: 'itemjoin.darkzone.flare'
```
