### ISSUE TITLE
Remember items replaced.

### ISSUE THREAD

**Issue by ziemniok99** [RockinChaos/ItemJoin#217]
## Thanks for taking the time to open a feature/bug request!

**[ Resource Questions / Help and Support ]**
If you have a question or are seeking support for one of my Resources, please make
sure you reply with the proper formatting shown below.

**Once the following information is provided I will reply to you as quick as possible!**
1.) The version of the Resource. Not neccesary
2.) Version of the Spigot / Craftbukkit / Cauldron / ETC. Not neccesary
3.) What is the problem that you are having? When I setup items in certain region and player will join with full inventory, plugin should rmember his old inventory and give from ItemJoin. When player leave region it will give his old items.
4.) Post all your YAML / Configuration files, please include a Pastebin.com link. Not neccesary
5.) Post any error codes found in your console window if it pertains to this issue, please include a Pastebin.com link. Not neccesary

**Comment by RockinChaos** [comment]
Not quite sure what you are asking for. ItemJoin doesn't really do any inventory management all it really does it give players items upon certain events. 

So you are wanting a players inventory to fully removed and replace with ItemJoin items upon entering a region and restore it upon exiting the region?

**Comment by ziemniok99** [comment]
Yes exactly

**Comment by RockinChaos** [comment]
Okay, I will see what I can do. Its a pretty simple process but I have to account for players logging off inside the region and the server restarting which means I have to store the player data somewhere and all of their items might become obfuscated but Ill see if I can figure something out.

**Comment by RockinChaos** [comment]
Okay, so I have added this feature in the latest snapshot and will be available in the v5.0.4 release.
http://ci.craftationgaming.com/job/ItemJoin/

How it works:
There is now the option to clear the player's inventory when entering a specific region or all regions under clear-items in the config.yml. (you will need to add it or regenerate the config.yml).

Now to return the items you must specify the `Options: RETURN` under clear-items in the config.yml. Upon exiting each region the cleared inventory will be returned.

You can also specify the clearing / returning of all items or ItemJoin only items.
Examples;
```
Clear-Items:
  Type: ITEMJOIN
  Delay-Tick: 2
  Join: DISABLED
  World-Switch: DISABLED
  Region-Enter: region1, region2
  Options: PROTECT, RETURN
  Bypass: OP
```
or
```
Clear-Items:
  Type: ALL
  Delay-Tick: 2
  Join: DISABLED
  World-Switch: DISABLED
  Region-Enter: true
  Options: RETURN
  Bypass: OP
```
