### ISSUE TITLE
Item click-through

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#225]
Spigot 1.14.4 latest or Spigot 1.13.2 final
ItemJoin 5.0.4-b285
DeluxeMenus 1.12.0
Skript 2.4-beta5

Right-click on CLOCK item opens the DeluxeMenus menu, but also acts on the iron_door at which the click is aimed, which triggers a Skript to toggle the iron_door. This occurs even though _itemflags_ includes _cancel-events_. The issue does not occur if the right-click would trigger a vanilla toggle event (for example, if the target were a wooden door).

Similar to, or perhaps reappearance of, #163.

ItemJoin items.yml (relevant portion):
```
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    enchantment: FIRE_ASPECT:1
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    enabled-worlds: world, world_lobby, world_blackdog
```
and config.yml (sans comments):
```
config-Version: 7

Language: 'English'

General:
  CheckforUpdates: false
  Metrics-Logging: false
  Log-Coloration: false
  Log-Commands: true
  Debugging: false

Settings:
  HeldItem-Slot: 0
  DataTags: true

Permissions:
  Obtain-Items: false
  Obtain-Items-OP: false
  Commands-Get: false
  Commands-OP: false
  Movement-Bypass: false

Clear-Items:
  Type: ITEMJOIN
  Delay-Tick: 2
  Join: DISABLED
  World-Switch: DISABLED
  Options: PROTECT
  Bypass: DISABLED

Active-Commands:
  commands:
    - 'itemjoin get <item> <player>'
    - 'first-join: say This is a command only executed once per world, per player.'
  triggers: JOIN
  enabled-worlds: DISABLED

Prevent:
  Pickups: DISABLED
  itemMovement: DISABLED
  Bypass: DISABLED

softDepend:
  Multiverse-Core: true
  Multiverse-Inventories: true
  PlaceholderAPI: true
  Vault: true
  WorldGuard: true

  AuthMe: false
  BetterNick: false
  HeadDatabase: false
  MyWorlds: false
  PerWorldInventory: false
  PerWorldPlugins: false
  TokenEnchant: false
  xInventories: false
```
and the Skript:
```
on rightclick on iron door:
	toggle the block
	cancel the event
```
