### ISSUE TITLE
[Suggest] 

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#236]
ItemJoin is very powerful and efficiency now. There may no any important things to do. If you want to add more feature, you can look at it. Thank you for spending a lot of time updating ItemJoin.

**1. Custom disposable conditions.**
Only some situation will execute commands and consume that item. It can be very useful to create a special item for other plugin. For example, a pet skill ticket. If player has a pet, it will change his pet's skill. Otherwise it will show a failure message. 
`
Condition:
- '%mypet_has_pet%:equal:true'
- '%other_placeholder%:notequal:VALUE'
- '%other_placeholder%:over:100'
- '%other_placeholder%:under:200'`
`fail-message: '&cYou need to summon your pet.'`
*Some placeholder equal null. You need to check it, if the value equal "".*
*%other_placeholder%:equal:*

**2. More triggers.**
- Custom recipe
https://www.spigotmc.org/wiki/recipe-example/
- Kill mobs
mobs-drop:
`- 'ZOMBIE:0.001'
- 'Crazy_Zombie:0.002'
- Break blocks`
blocks-drop:
`- 'DIAMOND_ORE:0.1'
- 'GOLD_ORE:0.01'`

**3. Random commands.**
More custom way to select a command.
`- <chance:0.9> say 0.9 / ( 0.9 + 0.1 + 0.2 ) * 100% = 75%
- <chance:0.1> say 0.1 / ( 0.9 + 0.1 + 0.2 ) * 100% = 8.3%
- <chance:0.2> say 0.2 / ( 0.9 + 0.1 + 0.2 ) * 100% = 16.7%`

This is a example
`   // To get a random number below total chance.
    double radomTotalChance = Math.round(Math.random() * totalChance);
   
    for (String command : commandList){
        // To get that command's change. I don't know how to get it from "<chance:0.9>".
        double chance = ConfigHandler.getConfig("config.yml").getDouble(command + ".chance");
        // Compare the chance and the number below total chance.
        if (chance >= radomTotalChance) {
            return ExecuteCommand;
        }
        // To minus the chance and let it no longer be included in the total chance.
        // For example, a random number below "1.2" is "1.15".
       // If it is over "0.9", it will minus 0.9 and change to "0.25".
       // If it is over "0.1", it will minus 0.1 and change to "0.15".
       // It is under "0.2" then execute commands.
        radomTotalChance -= chance;
    }`

**4. Custom food**
ItemJoin can custom the golden apple, but it will be more interesting if we can add any potion effect by click a custom item like a skull 'Apple Cake'. And using less CPU performance if we directly using the Spigot API, not commands. The potion effect's format could be the golden apple's.
`potion-effect: JUMP:2:120, NIGHT_VISION:2:400, GLOWING:1:410, REGENERATION:1:160`

**Comment by RockinChaos** [comment]
Okay so currently I have added all requested features for no.3 (Recipes, Mobs-Drop. and Blocks-Drop) available in the latest snapshot for testing; http://ci.craftationgaming.com/job/ItemJoin/430/

Here is how you should set up each use-case (you can do this in the `/itemjoin menu` WAY easier.)

* Mobs Drop
  * You can now specify a list of mobs and their probability of dropping the custom item.
  * A probability of 1.0 is the max probability and is considered to be 100%.
  * Formatting is ENTITY:PROBABILITY.
  * The Entity expects an entity type input, obviously all entities will not work such as an ender pearl. The entity input should be a physical mob. List of entities here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  * Recommendations (not required): Set triggers to DISABLED to prevent players from getting the items on join. Set the slot of ARBITRARY--there is no real reason for this but it can help with compatibility in the future.
```
  mobs-item:
    id: IRON_SWORD
    slot: ARBITRARY
    name: '&cStolen Sword'
    lore:
    - '&7Pulled from the ashes of chaos.'
    mobs-drop:
    - 'ZOMBIE:0.001'
    - 'PIG:0.3'
    triggers: DISABLED
    enabled-worlds: world, world_the_end
```
* Blocks Drop
  * You can now specify a list of mobs and their probability of dropping the custom item.
  * A probability of 1.0 is the max probability and is considered to be 100%.
  * Formatting is MATERIAL:PROBABILITY.
  * The Material expects a block type input, obviously all materials will not work such as a COOKED_STEAK. The block input should be a physical block. List of materials here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  * Recommendations (not required): Set triggers to DISABLED to prevent players from getting the items on join. Set the slot of ARBITRARY--there is no real reason for this but it can help with compatibility in the future.
```
  blocks-item:
    id: DIAMOND_BLOCK
    slot: ARBITRARY
    name: '&aSurprise!'
    mobs-drop:
    - 'ZOMBIE:0.001'
    - 'PIG:0.3'
    triggers: DISABLED
    enabled-worlds: All
```
* Custom Recipe.
  * You can now specify a recipe for a custom item.
  * To define a recipe, you must specify the shape with the ingredient characters, as well as the ingredients with their characters. The ingredients expect a single character followed by the material input. See the example item below.
  * Recipe shapes are quite diverse and can be defined in unique shapes as shown.
  * X Stands for Air, do NOT include X in the 'ingredients' below.
  * Examples of Recipe usages:
```
    recipe:
    - 'XGX'
    - 'IDI'
    - 'XGX'
    recipe:
    - 'XG'
    - 'XD'
    recipe:
    - 'XGX'
    - 'IDI'
    recipe:
    - 'G'
    - 'D'
    - 'G'
```

```
  recipe-item:
    id: BEDROCK
    slot: ARBITRARY
    name: '&6Essence'
    lore:
    - '&7Shhhh don''t tell anyone...'
    recipe:
    # X Stands for Air, do NOT include X in the 'ingredients' below.
    - 'XGX' # First row in the crafting table
    - 'IDI' # Second row in the crafting table
    - 'XGX' # Third row in the crafting table
    ingredients:
    # Format: LETTER:ITEMID
    - 'G:GOLD_INGOT' # G Stands for Gold Ingot.
    - 'I:IRON_INGOT' # I Stands for Iron Ingot.
    - 'D:DIAMOND' # D Stands for Diamond, you can use any letter here and the ITEMID can be numerical.
    triggers: DISABLED
```

Additional info can be found here; https://github.com/RockinChaos/ItemJoin/wiki/DevLog
