### ISSUE TITLE
Illegal item movement

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#247]
Spigot 1.15.2 (Jenkins 2629)
Multiverse-Inventories 4.0.0-b467
ItemJoin 5.0.6-b363

I was able to move a locked item from the target slot to another slot. This should not be possible. The method:
- Open the player inventory (E)
- Engage CAPSLOCK key (so it remains lit)
- Randomly press number keys 1-5 until the CLOCK item moves

The recipe is repeatable. The CLOCK item moves to slot 2 (0-based), which was empty (all slots except 8 were empty). I have not been able to move it back to the original position (slot 8).

ItemJoin/config.yml
```
config-Version: 7
Language: 'English'
General:
  CheckforUpdates: false
  Metrics-Logging: false
  Log-Coloration: false
  Log-Commands: true
  Debugging: false
Settings:
  HeldItem-Slot: 0
  DataTags: true
Permissions:
  Obtain-Items: false
  Obtain-Items-OP: false
  Commands-Get: false
  Commands-OP: false
  Movement-Bypass: false
Clear-Items:
  Type: ITEMJOIN
  Delay-Tick: 2
  Join: DISABLED
  World-Switch: DISABLED
  Options: PROTECT
  Bypass: DISABLED
Active-Commands:
  commands:
    - 'itemjoin get <item> <player>'
    - 'first-join: say This is a command only executed once per world, per player.'
  triggers: JOIN
  enabled-worlds: DISABLED
Prevent:
  Pickups: DISABLED
  itemMovement: DISABLED
  Bypass: DISABLED
softDepend:
  Multiverse-Core: true
  Multiverse-Inventories: true
  PlaceholderAPI: true
  Vault: true
  WorldGuard: true
  AuthMe: false
  BetterNick: false
  HeadDatabase: false
  Multiverse-Core: true
  Multiverse-Inventories: true
  MyWorlds: false
  PerWorldInventory: false
  PerWorldPlugins: false
  PlaceholderAPI: true
  TokenEnchant: false
  Vault: true
  WorldGuard: true
  xInventories: false
```
ItemJoin/items.yml
```
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    enchantment: FIRE_ASPECT:1
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    enabled-worlds: world, world_lobby, world_blackdog, world_city, world_luckyblock, world_minigames, world_skyblock, world_westeros, world_whitedog, world_yellowdog
```
