### ISSUE TITLE
hide-attributes not honored

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#251]
Spigot 1.15.2
ItemJoin 5.0.6-b364

items.yml includes
```
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    enchantment: FIRE_ASPECT:1
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
```
but item attributes are displayed. Please advise what I am doing wrong.

![Screen Shot 2020-02-26 at 8 53 35 PM](https://user-images.githubusercontent.com/17748923/75413775-5a0b6600-58db-11ea-8404-7b63ba4660c1.png)
