### ISSUE TITLE
Amusing WeaponHolder glitch

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#256]
Spigot 1.15.2
ItemJoin 5.0.6-b366
[WeaponHolder](https://www.spigotmc.org/resources/weaponholder.75080/) 1.5

This may well be a WeaponHolder issue, but I'll start here to verify that it isn't an IJ issue.

If I (accidentally) place a locked IJ item on a WeaponHolder tripwire-hook, it accepts the item (ie., it is removed from inventory slot and placed on the tripwire-hook). When I take the item back, it is locked into a different inventory slot (the first available, left-to-right).

items.yml
```
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation'
    enchantment: FIRE_ASPECT:1
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
```
