### ISSUE TITLE
[Request] Support custom items between difference servers.

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#263]
I have a problem that some custom items can not be identified between two servers.
(I use "MySQL Player Data Bridge" to sync the player's inventory.)

They have the same configurations, but generated in difference server.
And their item NBTs are difference too.
(ItemJoin Slot (String): Arbitrary3  & ItemJoin Slot (String): Arbitrary4)

Is any way to allow custom items between two servers? 
Like a new option "Low-Level-ItemNBT-Identify" to ignore the Arbitrary?

The configuration in items.yml.
```
  fly:
    slot: Arbitrary
    id: PAPER
    name: '&b&l飛行券 &f(10分鐘) &f&l兌換券'
    enchantment: FIRE_ASPECT:1
    lore:
    - '&a自由飛行蓋家囉！'
    - '&f將自動切換至飛行模式'
    - '&6&l拿著左鍵點擊使用&4✌'
    - ''
    - '&d&l取得來源: &e特殊活動物品'
    commands:
      left-click:
      - 'message: &6&l你使用了&c✤ &b&l飛行券 &f(10分鐘) &f&l兌換券'
      - 'console: lp user %player% parent addtemp s-fly 10m accumulate'
      - 'console: cmi fly %player% true'
    commands-type: interact
    commands-sound: ENTITY_PLAYER_LEVELUP
    itemflags: hide-attributes, disposable, always-give, cancel-events, drop-full
    triggers: disabled
    permission-node: itemjoin.myitem
    enabled-worlds: All
```

First server's new item NBT.
![](https://imgur.com/sSpdf5E.png)

Another server's new item NBT.
![](https://imgur.com/jKXvagg.png)

Full items.yml.
First: https://pastebin.com/NeEed4c4
Second: https://pastebin.com/NeEed4c4
---
ItemJoin version: v5.0.6-SNAPSHOT-b364
Paper version: git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Thank you for updates : )

**Comment by momoservertw** [comment]
Another custom item.
```

  slimecheck:
    id: BREWING_STAND
    slot: Arbitrary
    name: '&a&l黏液檢測器&4&l〄'
    enchantment: FIRE_ASPECT:1
    lore:
    - '&e檢測附近殘留的史萊姆黏液'
    - '&e得知是否有史萊姆出沒'
    - ''
    - '&d&l取得來源: &e贊助伺服器'
    commands:
      left-click:
      - 'message: &6&l你使用了&c✤ &a&l黏液檢測器&4&l〄'
      - 'op: motw give slimecheck'
    commands-type: interact
    commands-sound: ENTITY_PLAYER_LEVELUP
    itemflags: hide-attributes, disposable, always-give, drop-full
    triggers: disabled
    permission-node: itemjoin.myitem
    enabled-worlds: All
```

First server.
![](https://imgur.com/dUZOYKG)

Second server.
![](https://imgur.com/QGoC1Eg)
