### ISSUE TITLE
stop item from going into chest

### ISSUE THREAD

**Issue by TheChemist123** [RockinChaos/ItemJoin#284]
v5.0.6
Spigot
Hi i was wondering if there was a way to make it so that players are not able to move items from inventory into a chest? Thank you
https://pastebin.com/m3sP6Jym

thank you again and i hope you are well! <3

**Comment by RockinChaos** [comment]
This will stop the item from being stored;
`itemflags: item-store`

-- attaching this to your item.
```
  ultra-item:
    id: compass
    slot: 0
    name: '&aQuick Compass'
    commands:
      multi-click:
      - 'player: menu'
    commands-type: interact
    itemflags: item-store
    triggers: join, world-switch, respawn
    enabled-worlds: rss, arena, parkour
```


Let me know if this answered your question so I can close this. And I am well thanks for asking! Sadly, still very busy though haha.
