### ISSUE TITLE
Item commands.

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#285]
**[ Resource Questions / Help and Support ]**
Some problems with the item commands.
I am not sure if I have used these types of commands correctly.
```
multi-click: Execute command when clicked in inventory.
left-click: Execute command when clicked in inventory.
right-click: Execute command when clicked in inventory.

multi-click-air: Never executed
right-click-air: Never executed
left-click-air: Never executed

inventory: No problems.
```
Also, I have some suggestion.
I am using the menu plugin "BossShopPro" which has some great command types.
You can refer to it~ The command type of inventory will be more abundant!
- inventory-left
- inventory-right
- inventory-middle (Mouse wheel)
- inventory-shift-left
- inventory-shift-right
- inventory-shift-middle (BossShop does not have this feature, but maybe you can try it?)

In addition, is it possible to add the "Middle-Click" when players use the mouse wheel.
And it may be clearer to distinguish the Click action from the Inventory action?
***
**Once the following information is provided I will reply to you as quick as possible!**
1. ItemJoin version: v5.0.6   (release)
2. Paper version: Paper version git-Paper-245 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) (latest)
3. Test server and default config.yml.
4. item.yml - https://pastebin.com/usZpPZUc
```
# --{ =-=-=-=-=-=-=-=-=-= ItemJoin's Custom Item Configurations, by RockinChaos =-=-=-=-=-=-=-=-=-= }--
# See the tutorial page for a more in-depth explaination; https://github.com/RockinChaos/ItemJoin/wiki
items-Version: 6
items-Delay: 2
items-Overwrite: false
items-Spamming: false
items-RestrictCount: false
items:
  test:
    id: STONE
    slot: 0
    name: '&bTest Stone'
    commands:
      multi-click:
        - 'message: multi-click'
      right-click:
        - 'message: right-click'
      left-click:
        - 'message: left-click'
      multi-click-air:
        - 'message: multi-click-air'
      right-click-air:
        - 'message: right-click-air'
      left-click-air:
        - 'message: left-click-air'
      inventory:
        - 'message: inventory'
    commands-type: interact, inventory
    itemflags: item-store, placement, death-drops, self-drops
    triggers: disabled
    permission-node: 'itemjoin.item.test'
    enabled-worlds: All
```
5.) Test video: https://youtu.be/57XyBMIIUDI?t=8

Thanks~ : )
