### ISSUE TITLE
Issue with items

### ISSUE THREAD

**Issue by Shlauf** [RockinChaos/ItemJoin#287]
I can't find a way to execute commands when item is right clicked and i really need it. If someone can help me please.

**Comment by RockinChaos** [comment]
https://github.com/RockinChaos/ItemJoin/wiki/Creating-Items#establishing-itemcommands

Here is an example;
```
click-item:
    id: EMERALD
    slot: 0
    name: '&aClicky Item'
    commands:
      right-click:
        - 'message: &eI am a right click!'
    commands-type: interact
    commands-sound: BLOCK_NOTE_PLING
    commands-cooldown: 5
    cooldown-message: '&7[&eItemJoin&7] &a[%item%&a] &cis on cooldown for &a%timeleft% &cseconds..'
    triggers: join, respawn, world-change, region-enter
    permission-node: 'itemjoin.ultra'
    enabled-worlds: world, world_nether, world_the_end
```
