### ISSUE TITLE
Delay doesn't affect on respawn and on world change

### ISSUE THREAD

**Issue by llaurenss** [RockinChaos/ItemJoin#29]
When I join a skywars game and leave the items are invisible and they become visible when i click on them.

Video:
https://www.youtube.com/watch?v=b1UrdgsjBJw&feature=youtu.be

This bug is really anoying but i understand if you can't fix it because the plugin isn't made for this.

Config:
```
#// <>==<>==<> ItemJoin's Custom Items On Join, by RockinChaos <>==<>==<> //#
#// See a list of variables for ItemJoin here: http://dev.bukkit.org/bukkit-plugins/itemjoin/pages/documentation //#
#// See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for item names! //#
#// See this enchantments page for the correct enchant name. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html //#
#// Need some more help with item slots? See the Documentations page for a more in-depth tutorial. http://dev.bukkit.org/bukkit-plugins/itemjoin/pages/documentation //#
#// For per-world support this best works with Multiverse-Inventories! http://dev.bukkit.org/bukkit-plugins/multiverse-inventories //#
#// Otherwise you will need to set clear-on-world-changed to true if you want to get the new items when you change worlds. //#
#// Then you will need to add give-on-modifiers (world-changed) to each item to receive the new items. //#
items-Version: 2

world-list: #// This is the list of worlds that have custom items on join. //#
  - spawn
#// For every world listed in the world-list, you need to make a section for it. //#
spawn:
  items:
    Ranked-Item:
      id: 276 #// Now supports item ID's! //#
      slot: 0
      data-value: 0
      name: '&aRanked Selector'
      commands:
        - 'ranked'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      First-Join-Item: false
      prevent-modifiers:
        - 'placement'
        - 'inventory-modify'
        - 'death-drops'
        - 'self-drops'
        - 'cancel-events'
        - 'item-damage-living'
        - 'item-damage-blocks'
        - 'AllowOpBypass'
        - 'CreativeBypass'
      give-on-modifiers:
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
        - 'CreativeBypass'
    Unranked-Item:
      id: 272 #// Now supports item ID's! //#
      slot: 1
      data-value: 0
      name: '&aUnranked Selector'
      commands:
        - 'unranked'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      First-Join-Item: false
      prevent-modifiers:
        - 'placement'
        - 'inventory-modify'
        - 'death-drops'
        - 'self-drops'
        - 'cancel-events'
        - 'item-damage-living'
        - 'item-damage-blocks'
        - 'AllowOpBypass'
        - 'CreativeBypass'
      give-on-modifiers:
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
        - 'CreativeBypass'
    Leave-Item:
      id: 35 #// Now supports item ID's! //#
      slot: 2
      data-value: 14
      name: '&cLeave the waiting quene!'
      commands:
        - 'battle leave'
      commands-action: RIGHT_CLICK_AIR, RIGHT_CLICK_BLOCK, LEFT_CLICK_AIR, LEFT_CLICK_BLOCK
      First-Join-Item: false
      prevent-modifiers:
        - 'placement'
        - 'inventory-modify'
        - 'death-drops'
        - 'self-drops'
        - 'cancel-events'
        - 'item-damage-living'
        - 'item-damage-blocks'
        - 'AllowOpBypass'
        - 'CreativeBypass'
      give-on-modifiers:
        - 'respawn'
        - 'world-changed'
        - 'AllowOpBypass'
        - 'CreativeBypass'
```

**Comment by RockinChaos** [comment]
can you send your config.yml? I think this can be fixed from your side easily.

**Comment by llaurenss** [comment]
The delay in the config is set to 2 seconds. And when i set it to 4 seconds it still spawns the items directly and the skywars plugin overriding the itemjoins items. The delay is only working on joining not on world changing i think.
Here is my config:
```
#// <>==<>==<> ItemJoin's Settings, by RockinChaos  <>==<>==<> //#
config-Version: 2
Language: 'English' #// English is currently the only support language at the moment! //#
CheckforUpdates: true #// Disable this if you dont want to be notified if there is an update. //#
PlaceholderAPI: false #// Only use this if PlaceholderAPI is installed on your server. Set to false else-wise. Required plugin restart when changed. //#
Multiverse-Core: false #// Using the Multiverse plugin? Enable this for complete use of all plugin features. Required plugin restart when changed. //#
Multiverse-Inventories: false #// Only used for plugin information. Set to false if you do not use it. Required plugin restart when changed. //#
#// Global-Settings for items. //#
Global-Settings: #// Global Settings, for each world listed under world-list. These will take effect in them. //#
  Prevention:
    prevent-pickups: false #// Prevents picking up of any item //#
    AllowOPBypass: false #// Ignores these settings under Prevention if you are OP //#
    CreativeBypass: false #// Ignores these settings under Prevention if you are in creative mode. //#
  Clear-On:
    clear-on-join: false #// Clears the players inventory upon entering the server. (Before items are given). //#
    clear-on-world-change: false #// Clears the players inventory upon changing worlds. (Before items are given). //#
    AllowOPBypass: false #// Ignores these settings under Clear-On if you are OP //#
  First-Join:
    FirstJoin-Mode-Enabled: false #// Set to true if you wish to use First-Join-Item: true per item! (This allows the use of the First Join options). //#
  Get-Items:
    ItemJoin-Specific-Items: true #// This meaning, these items are specific to ItemJoin and cannot be renamed to. Usually you would disable this if you had another plugin that hooks into ItemJoin items. //#
    Delay: 2 #// Set to 0 to disable. Recommended is 2 especially if you use First-Join! (This is in Seconds.) //#
```
