### ISSUE TITLE
Item names/lore not always displayed

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#304]
## Thanks for taking the time to open a bug report!

**Describe the bug**
Sometimes the item names and lore are displayed sometimes not. I have not discovered a consistent pattern, but it is new with Spigot 1.16.

**To Reproduce**
1. Define multiple IJ items in hotbar (slot 8) and not (slot 17) that activate based on permissions and worlds.
2. Open the inventory.
3. Observer that name/lore are not always displayed

**Expected behavior**
Consistent display of name and lore.

For example, this IJ item is configured for all worlds
```
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation4'
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    # disabled-worlds-UNSUPPORTED: world_void
    enabled-worlds: world, world_lobby, world_blackdog, world_city, world_luckyblock, world_minigames, world_skyblock, world_westeros, world_whitedog, world_yellowdog
```

.
**Screenshots**
In one world, correct
![Screen Shot 2020-07-03 at 12 09 34 PM](https://user-images.githubusercontent.com/17748923/86493511-b0276480-bd26-11ea-820c-ecde480d1e76.png)

In another world, incorrect
![Screen Shot 2020-07-03 at 12 09 02 PM](https://user-images.githubusercontent.com/17748923/86493501-a9005680-bd26-11ea-89bf-a64f91d8a8b1.png)

The navigation menu is popped in both cases, so the item definition basically works. Only the name and lore are problematic.

.
**Please complete the following information:**
```
>version
[11:56:22] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-beb7d47-145921e (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[11:56:22] [Server thread/INFO]: You are running the latest version
>version ItemJoin
[11:56:37] [Server thread/INFO]: ItemJoin version 5.0.7-SNAPSHOT-b448
[11:56:37] [Server thread/INFO]: Get custom items on join.
[11:56:37] [Server thread/INFO]: Website: https://www.spigotmc.org/resources/itemjoin.12661/
[11:56:37] [Server thread/INFO]: Author: RockinChaos
```
