### ISSUE TITLE
Count-lock does not lock rocket count while flying with elytra

### ISSUE THREAD

**Issue by Rick-Thompson** [RockinChaos/ItemJoin#308]
I have rockets count-locked at 64. They refill when launched in the air while standing on the ground but when flying they do not refill.

I am running build 471 but it still has the same issue on the older builds. Running on server spigot 1.16.1

My items.yml

```
#// <>==<>==<> ItemJoin's Custom Items On Join, by RockinChaos <>==<>==<> //#
#// See the Documentations page for a more in-depth tutorial; https://www.spigotmc.org/wiki/itemjoin/ //#
items-Version: 6
items-Delay: 2
items-Overwrite: false
items-Spamming: false
items-RestrictCount : true

items:
    elytra-item:
      id: ELYTRA
      slot: Arbitrary
      triggers: join, respawn, world-change
      itemflags: unbreakable
    food-item:
      id: bread
      slot: Arbitrary
      count: 16
      itemflags: first-join
    rocket-item:
      id: FIREWORK_ROCKET
      slot: Arbitrary
      itemflags: count-lock
      count: 64
      triggers: join, respawn, world-change
```
