### ISSUE TITLE
Problem with the cooldown.

### ISSUE THREAD

**Issue by BlueShadows47** [RockinChaos/ItemJoin#309]
Hello !
I have a problem:
Unable to add a countdown on my items ...
Here is my configuration:
```
  duel-gapples:
    id: DIAMOND_SWORD
    slot: 0
    name: '&bDuel | GApples'
    use-cooldown: 10
    lore:
    - '&7Cliquez pour lancer un duel GApples.'
    commands:
      left-click:
      - 'delay: 10'
      - 'player: queue join GApples 0'
      right-click:
      - 'delay: 10'
      - 'player: queue join GApples 0'
    commands-type: interact
    commands-sound: BLOCK_NOTE_PLING
    commands-sequence: SEQUENTIAL
    cooldown-message: '&cVeuillez patienter 10 secondes...'
    enchantment: FIRE_ASPECT:3, DAMAGE_ALL:5, DAMAGE_UNDEAD:5, KNOCKBACK:8
    itemflags: unbreakable, hide-attributes, self-drops, death-drops, CreativeBypass
    triggers: join, respawn, world-switch, region-enter
    permission-node: itemjoin.ultra
    enabled-regions: region1, region2
    enabled-worlds: world, world_nether, world_the_end, duel`
```
Bye. ^^
