### ISSUE TITLE
Map images breaking on server restart

### ISSUE THREAD

**Issue by BlitzGamer-88** [RockinChaos/ItemJoin#311]
So I've just started using this plugin and I found the feature of adding images on maps very interesting so I decided to use it. I added my server logo to the folder made an item which can be seen bellow and took the logo and made resized it to 128 x 128 pixels. The map works until I restart the server. When I do `/stop` or I press the stop button from the console start the server again the map resets and I get this: https://i.imgur.com/qOiF2Ye.png which is a starting of a rendering of my lobby/spawn. To reset this I need to clear my inventory. It does happen when I am and when I am not op.

I've made this item: 

```
  server-logo:
    id: FILLED_MAP
    custom-map-image: server-icon.png
    slot: 4
    name: '&ePlay...'
    itemflags: item-store, item-craftable, item-modifiable, unbreakable, hide-attributes, death-drops, self-drops, placement, inventory-modify
    triggers: join, respawn, world-switch, region-enter
    enabled-worlds: world
```
then restarted the server

Items.yml: https://paste.helpch.at/nemagifitu.php
Config.yml: https://paste.helpch.at/ozilanazoy.php
Photo proprieties: https://imgur.com/a/aJYnrlv

Server version:
```
[01:28:29 INFO]: This server is running Paper version git-Paper-83 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[01:28:29 INFO]: You are 3 version(s) behind
```
ItemJoin version:
```
[01:29:01 INFO]: ItemJoin v5.0.6-RELEASE-b395 by RockinChaos
[01:29:01 INFO]: Type /ItemJoin Help for the help menu.
```
