### ISSUE TITLE
HeldItem-Slot not working on world change

### ISSUE THREAD

**Issue by juancruzdal** [RockinChaos/ItemJoin#317]
Plugin version: 5.0.6-RELEASE-b395
Spigot: Paper 1.8.8

I set in the config this:
```
Settings:
  HeldItem-Slot: 2
  HeldItem-Triggers: JOIN, WORLD-SWITCH
  DataTags: true
```
