### ISSUE TITLE
No right-click?

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#326]
## Thanks for taking the time to open a bug report!

**Describe the bug**
No right-click action (no change to IJ configuration) with
Spigot 1.16.2 (Jenkins 2869)
ProtocolLib 4.6.0-SNAPSHOT-b476
ItemJoin 5.0.7-SNAPSHOT-b509

**Configuration**
```
# --{ =-=-=-=-=-=-=-=-=-= ItemJoin's Configuration Settings, by RockinChaos =-=-=-=-=-=-=-=-=-= }--
# See the tutorial page for a more in-depth explaination; https://github.com/RockinChaos/ItemJoin/wiki
config-Version: 7

Language: 'English'

# These are typically general maintenance settings that do not affect functionality.
General:
  CheckforUpdates: false
  Metrics-Logging: false
  Log-Coloration: false
  Log-Commands: true
  Debugging: false

# These settings are optional as a database file is generated by default or you can setup MySQL database connections.
Database:
  MySQL: false
  host: 'localhost'
  port: 3306
  table: 'database_name'
  user: 'root'
  pass: 'password'

# These settings will take effect globally throughout the plugins system.
Settings:
  HeldItem-Slot: 0
  HeldItem-Triggers: JOIN, WORLD-SWITCH
  DataTags: true

# These permissions if enabled, determine whether the permission(s) is/are applied to certain players.
Permissions:
  Obtain-Items: false
  Obtain-Items-OP: false
  Commands-Get: false
  Commands-OP: false
  Movement-Bypass: false

# If enabled this will clear items from their inventory upon performing the specified action for the specified type.
# The available types(s) are ALL for all items or ITEMJOIN for only the ItemJoin items.
Clear-Items:
  Type: ITEMJOIN
  Delay-Tick: 2
  Join: DISABLED
  World-Switch: DISABLED
  Region-Enter: DISABLED
  Options: PROTECT, PROTECT_OP, PROTECT_CREATIVE
  Blacklist: '{id:BEDROCK}, {slot:4}, {name:Blazefury}'

# This is the command(s) executed upon the player performing the defined trigger(s), for the specified world(s).
Active-Commands:
  commands:
    - 'itemjoin get <item> <player>'
    - 'first-join: say This is a command only executed once per world, per player.'
  triggers: JOIN
  enabled-worlds: DISABLED

# This determines if the action is allowed for all items in the specified worlds.
# To disable an action, simply set the action to true for all worlds or list each world separated by a comma.
Prevent:
  Pickups: DISABLED
  itemMovement: DISABLED
  Self-Drops: DISABLED
  Death-Drops: DISABLED
  Bypass: DISABLED

# These are optional dependencies, only enable these if you want to use them.
softDepend:
  Multiverse-Core: true
  Multiverse-Inventories: true
  PlaceholderAPI: true
  Vault: true
  WorldGuard: true

  AuthMe: false
  BetterNick: false
  HeadDatabase: false
  MyWorlds: false
  PerWorldInventory: false
  PerWorldPlugins: false
  TokenEnchant: false
  xInventories: false
```
```
items:
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      right-click:
        - 'deluxemenus open navigation4'
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
```

**Expected behavior**
Previously, DeluxeMenu opened.

**Additional context**
Player has permission `deluxemenus.open`

I changed the command to
```
    commands:
      right-click:
        - 'say deluxemenus open navigation4'
```
which also did not execute. The clock did "click".
