### ISSUE TITLE
Item Book

### ISSUE THREAD

**Issue by Yassounou** [RockinChaos/ItemJoin#331]
Hello, 

what item flag can i add to  book-item: , so a player get it once and only on first join ?
thnx

**Comment by RockinChaos** [comment]
To do this you add the first-join trigger.

Example;
```
  example-item:
    id: DIAMOND_SWORD
    slot: 0
    triggers: first-join
```
