### ISSUE TITLE
(Possible Bug) Exeption on task 122806.

### ISSUE THREAD

**Issue by DarkKingKaanMC** [RockinChaos/ItemJoin#347]
## Thanks for taking the time to open a bug report!

**Describe the bug**
I'm getting an error message about an Exeption on task 122806.

**To Reproduce**
1. Join the server.
2. See the error in console. 

**Expected behavior**
There should not be any errors in console.

**Pastebin**
https://pastebin.com/wxCHsMhw

**Please complete the following information:**
 - Resource Version and Build Number: Latest.
 - Server Version [e.g. Spigot-1.15.2]: Latest Paper 1.15.2 (git-Paper-390)

**Additional context**
I'm using Triton for server translating and translations are only visible when I interact with an item. Otherwise, the variables can be seen. I doubt this is a problem with them but I will notify them anyway.

**Comment by RockinChaos** [comment]
Duplicate of #337 

Please use the latest snapshot; https://ci.craftationgaming.com/job/ItemJoin/580/

**Comment by DarkKingKaanMC** [comment]
The error seems to be gone after trying it with the snapshot.

The issue, stated in *Additional context*,  is still present.
The variables are updated only when a click action is run.

Any idea how I could fix this?

**Comment by RockinChaos** [comment]
I apologize for the late reply! I completely missed what you put in the additional context.
The URL for your pastebin seems to have expired but I think this issue occurs because you are missing the `dynamic` itemflag.

Try adding that and let me know.

**Comment by DarkKingKaanMC** [comment]
It's alright. Unfortunately, this didn't fix my issue. The items _did_ update every 100 ticks, but that's also pretty slow and the placeholders become "active" only when I click on the item or if I interact with it.

**Comment by RockinChaos** [comment]
I apologize again for the late reply, apparently, my posts on Github are not posting.

So I *think* I know what you are looking for, you add an update delay to let's say 20 ticks (1 second), you can manually change this. By default, the update delay is at 100 ticks as you said above.

Here is an example for an item that updates both the name/lore at a fixed rate, you can change these to be independent of each other or a shorter time period. If you want it to update faster than 20 ticks you will need to change `item-dirty-ticks` in the spigot.yml of your server to `1` as spigot manually limits the item update rate.

Format for the delay is `<delay:TICKRATE>`

Example;
```
items:
  dynamic-item:
    id: WATCH
    slot: 0
    name: '<delay:120>&a%server_online% Player(s) Online'
    lore:
      - '<delay:20>&7Current Server Uptime Is; %server_uptime%'
      - '&7%server_online% player(s) online.' #// This line does not need a delay, as the delay uses the first line of the lore (above).
    itemflags: dynamic, inventory-modify, hide-attributes
    enabled-worlds: world, world_nether, world_the_end
```



I am unsure exactly what you mean by `active` once you click the item, if this is completely independent of the dynamic updates can you please re-provide your items.yml so I can debug this issue.

I apologize for all the confusion, since the second issue was put under additional context I missed it when debugging the original error you posted.
