### ISSUE TITLE
Item doesn't trigger DeluxeMenus

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#360]
## Thanks for taking the time to open a bug report!

**Describe the bug**
New IJ 5.2.0 does not trigger DeluxeMenus. Same configuration worked with IJ 5.1.1-b660. IJ items exist, but do not trigger DM action.

**To Reproduce**
1. Update ItemJoin to 5.2.0-b661; no other server changes
2. Start server
3. Connect to server
4. Click on menubar item in slot 8

items.yml (partial)
```
# --{ =-=-=-=-=-=-=-=-=-= ItemJoin's Custom Item Configurations, by RockinChaos =-=-=-=-=-=-=-=-=-= }--
# See the tutorial page for a more in-depth explanation; https://github.com/RockinChaos/ItemJoin/wiki
items-Version: 7

# General options that apply to the custom items functionality.
items-Delay: 2
items-Overwrite: true
items-Spamming: false
items-RestrictCount : true

items:
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    commands:
      interact-right:
      - 'player: deluxemenus open navigation4'
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    enabled-worlds: world, world_lobby, world_blackdog, world_city, world_luckyblock, world_minigames, world_skyblock, world_westeros, world_whitedog, world_yellowdog
```

**Expected behavior**
DeluxeMenus menu should open.

**Please complete the following information:**
 - Resource Version and Build Number: 5.2.0-b661
 - Server Version: Spigot 1.16.5-3002 or Paper 1.16.5-457

**Comment by RockinChaos** [comment]
Not a bug, there was a major version change (v5.1.1 to v5.2.0) which is intended to show there was a critical change in the configuration files.

As stated as a warning for the build prior to downloading the `commands:` identifier has been removed.

Meaning your item should now look like this;
```
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    interact-right:
    - 'player: deluxemenus open navigation4'
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    triggers: join, respawn, world-change
    permission-node: 'deluxemenus.open'
    enabled-worlds: world, world_lobby, world_blackdog, world_city, world_luckyblock, world_minigames, world_skyblock, world_westeros, world_whitedog, world_yellowdog
```

This was done to simplify the items.yml since having the commands identifier is kinda redundant now and is essentially legacy code. Now all you need to do is specify the command-action such as interact-right.
