### ISSUE TITLE
Placeholders "%item_node%", %item_name% and dependence item files.

### ISSUE THREAD

**Issue by momoservertw** [RockinChaos/ItemJoin#365]
**Please describe your question or what you need help with, in the best detain you can.**
Recently, I created a new server and added many new items. One of the series is emoticon tickets, there are "21" types. I set them to the same format and only changed the item node and display name. I will create other series later, such as particle ticket, bow particle ticket...

For these reasons, my "item.yml" file may exceed two thousand lines, and it is hard to edit items. In addition, adding new series will take a lot of time.

For example,
```
em_1:   # em_Number <- The number of series.
    slot: Arbitrary
    id: PAPER
    enchantment: FIRE_ASPECT:1
    name: '&e&lEmotes Ticket &7(Smile)'  # Display name
    lore:
    - 'To get a emote.'
    interact-left:
      - 'message: &6You use &c✤ &e&lEmotes Ticket &7(Smile)'  # Display name
      - 'console: lp user %player% permission set emotes.type.em_1'  # itemNode
    itemflags: disposable
    triggers: disabled
    permission-node: itemjoin.item
```

First problem is "creating lots of similar items will cost lots of time".
=> adding placeholders "%item_node%", "%item_name%".

- `message: &6You use &c✤ &e&lEmotes Ticket`
-> message: &6You use &c✤ &f%item_name%
- `console: lp user %player% permission set emotes.type.em_1`
-> console: lp user %player% permission set emotes.type.%item_node%

We will only need to change the number of that item and give them a display name.

Second problem is "To many series and items".
=> Loading independence item files in the folder "items".
This will take some time to change it. I don’t know if this will be troublesome for you. QQ

Happy new year~ I'm Taiwanese, my family is celebrating the Chinese New Year new. haha
