### ISSUE TITLE
IJ item not restored on respawn

### ISSUE THREAD

**Issue by SlimeDog** [RockinChaos/ItemJoin#407]
## Thanks for taking the time to open an assistance request!

**Please describe your question or what you need help with, in the best detain you can.**
When I die and respawn, my ItemJoin items are not restored. This is a test server, so I don't die very often, but I believe this is a new phenomenon.

**Please complete the following information:**
 - Resource Version and Build Number: 5.2.3-b736
 - Server Version Spigot-1.17-3162

**items.yml**
```
items-Version: 8

items-Delay: 2
items-Overwrite: true
items-Spamming: false
items-RestrictCount: true

items:
  changeWorld-tool:
    id: CLOCK
    slot: 8
    count: 1
    name: '&bNavigate'
    lore:
      - 'Teleport elsewhere'
    interact-right:
    - 'player: deluxemenus open navigation4'
    itemflags: cancel-events, death-drops, hide-attributes, hide-durability, inventory-modify, placement, self-drops, unbreakable
    permission-node: 'deluxemenus.open'
    # disabled-worlds-UNSUPPORTED: world_void
    enabled-worlds: world, world_lobby, world_blackdog, world_city, world_luckyblock, world_minigames, world_skyblock, world_westeros, world_whitedog, world_yellowdog
```

** config.yml**
```
config-Version: 8

Language: 'English'

General:
  CheckforUpdates: false
  Metrics-Logging: false
  Log-Coloration: false
  Log-Commands: true
  Debugging: false

Database:
  MySQL: false
  database: 'database_name'
  prefix: 'ij_'
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: 'password'

Settings:
  HeldItem-Slot: 0
  HeldItem-Triggers: JOIN, RESPAWN, WORLD-SWITCH
  HeldItem-Animations: false
  Default-Triggers: JOIN
  DataTags: true

Permissions:
  Obtain-Items: false
  Obtain-Items-OP: false
  Commands-Get: false
  Commands-OP: false
  Movement-Bypass: false

Clear-Items:
  Type: ITEMJOIN
  Delay-Tick: 2
  Join: false
  Quit: false
  World-Switch: false
  Region-Enter: false
  Options: PROTECT, PROTECT_OP, PROTECT_CREATIVE
  Blacklist: ''

Active-Commands:
  commands:
    - 'itemjoin get <item> <player>'
    - 'first-join: say This is a command only executed once per world, per player.'
  commands-sequence: SEQUENTIAL
  triggers: JOIN
  enabled-worlds: DISABLED

Prevent:
  Pickups: false
  itemMovement: false
  Self-Drops: false
  Death-Drops: false
  Bypass: DISABLED

softDepend:
  Multiverse-Core: true
  Multiverse-Inventories: true
  PlaceholderAPI: true
  Vault: true
  WorldGuard: true

  AuthMe: false
  BetterNick: false
  HeadDatabase: false
  MyWorlds: false
  PerWorldInventory: false
  PerWorldPlugins: false
  TokenEnchant: false
  xInventories: false
```
