### ISSUE TITLE
Respawn trigger doesn't work

### ISSUE THREAD

**Issue by StupidRepo** [RockinChaos/ItemJoin#409]
## Thanks for taking the time to open a bug report!

**Describe the bug**
When the player first joins the overworld, they get start items. When they die, I want them to get the items after they re spawn
```
  starter-tools-pick:
    id: WOODEN_PICKAXE
    slot: 1
    name: 'Starter Pickaxe'
    triggers: first-join, respawn
    enabled-worlds: world
```
So I set the trigger but alas, when the player dies and respawn, they don't get the items.

**Expected behavior**
When player respawns after death, they should get items.

**Screenshots**

**Pastebin**
```
# --{ =-=-=-=-=-=-=-=-=-= ItemJoin's Custom Item Configurations, by RockinChaos =-=-=-=-=-=-=-=-=-= }--
# See the tutorial page for a more in-depth explanation; https://github.com/RockinChaos/ItemJoin/wiki
# Join the discord for easy plugin support; https://discord.gg/D5FnJ7C
# 
# Modifying the Version will cause this file to break and regenerate.
items-Version: 8
items-Delay: 0
items-Overwrite: true
items-Spamming: false
items-RestrictCount: false
items:
  starter-tools-sword:
    id: WOODEN_SWORD
    slot: 0
    name: 'Starter Sword'
    triggers: first-join, respawn
    enabled-worlds: world
  starter-tools-pick:
    id: WOODEN_PICKAXE
    slot: 1
    name: 'Starter Pickaxe'
    triggers: first-join, respawn
    enabled-worlds: world
  starter-tools-axe:
    id: WOODEN_AXE
    slot: 2
    name: 'Starter Axe'
    triggers: first-join, respawn
    enabled-worlds: world
  starter-armour-boots:
    id: LEATHER_BOOTS
    slot: 3
    name: 'Mouldy Boots'
    triggers: first-join, respawn
    enabled-worlds: world
  starter-armour-hat:
    id: LEATHER_HELMET
    slot: 4
    name: 'Mouldy Hat'
    triggers: first-join, respawn
    enabled-worlds: world
```

**Please complete the following information:**
 - Resource Version and Build Number: [e.g. 5.0.6-b364] ???
 - Server Version [e.g. Spigot-1.15.2] Paper 1.16.5

**Additional context**
