### ISSUE TITLE
Is it possible to make an item undroppable, while allowing other items to be dropped?

### ISSUE THREAD

**Issue by Anim3Add1ct** [RockinChaos/ItemJoin#411]
I want to make an item undroppable by the players, while allowing normal Minecraft items to be dropped. Enabling the Self-Drops option in config.yml disables dropping items altogether.

config.yml: https://pastebin.com/K9dBVMhk
items.yml: https://pastebin.com/7t7HtYF6

 - ItemJoin v5.2.2-RELEASE-b734
 - Paper 1.17.1

**Comment by RockinChaos** [comment]
You can do this via itemflags on your item instead.
Either in-game via `/itemjoin menu`

or simply add `itemflags: self-drops, death-drops` to your items.

Example;
```
  item_1: 
    id: NETHER_STAR
    interact: 
      - "player: helper"
    lore: 
      - ""
      - "&7Right-click me to open the helper!"
      - ""
    name: "&7[&c&lPrison Helper&7]"
    slot: 8
    triggers: JOIN
    itemflags: self-drops, death-drops
```
