### ISSUE TITLE
Colors Not Working

### ISSUE THREAD

**Issue by ky7969** [RockinChaos/ItemJoin#419]
Hello, the plugin is working flawlessly other than one thing. Color codes are not working, they dont work through the in game command or through config.

[config.yml](https://pastebin.pl/view/efb9a1d8)
[items.yml](https://pastebin.pl/view/c5fe336c)

Plugin Version: 5.2.2b734
Server Version: Paper-1.17.1

**Comment by RockinChaos** [comment]
Hmm so it seems the provided items.yml doesn't contain any color codes, maybe I am misunderstanding?

You are using the `&` symbol correct? Not the "double S"?

Example of one of your items using color codes;
```
  item_2:
    id: COMPASS
    slot: 0
    name: '&a&l&nWorld Selector'
    interact:
    - 'player: worldselector'
    commands-cooldown: 5
    cooldown-message: '&c&lPlease Wait %timeleft% Seconds Before Using That Again.'
    enabled-worlds: hub
```

I modified your cooldown-message and name as an example.
Let me know!~

If I am wrong, please clarify thanks!
