### ISSUE TITLE
You can throw EXP Bottles

### ISSUE THREAD

**Issue by Hartulino** [RockinChaos/ItemJoin#432]
ItemJoin v5.2.2
Hello. How do I disable players throwing the EXP Bottles? Thx

**Comment by RockinChaos** [comment]
I apologize for the late reply, I have been experiencing power outages due to a windstorm.
The itemflag `cancel-events` should work for this as it is similar to ender pearls.

Example; 
```
  exp-item:
    id: EXPERIENCE_BOTTLE
    itemflags: cancel-events
    triggers: join
    enabled-worlds: ALL
```
