### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by 2006lev-Web** [RockinChaos/ItemJoin#434]
How to make the item be issued 1 time and it could be thrown away

**Comment by RockinChaos** [comment]
I apologize for the late reply, I have been experiencing power outages due to a windstorm.

You can issue the item one time by using the `first-join` or `first-world` trigger.
The item can already be allowed the ability to be thrown away as long as you do not define the `self-drops` or `death-drops` itemflag. The `inventory-modify` itemflag can also be restrictive via click dropping.

Example item issued once;
```
  example-item:
    id: DIAMOND
    slot: 0
    triggers: first-join
    enabled-worlds: ALL
```

Let me know!~
