### ISSUE TITLE
Do not strip custom enchants from items.

### ISSUE THREAD

**Issue by ryantheleach** [RockinChaos/ItemJoin#455]
## Thanks for taking the time to open a feature request!

**Is your feature request related to a problem? Please describe.**
Various plugins implement custom enchants by registering into the base game.

**Describe the solution you'd like**
I would like ItemJoin to not strip enchantments, and support enchantments from namespaces other then Minecraft.

**Describe alternatives you've considered**
Forking ItemJoin.

**Comment by RockinChaos** [comment]
ItemJoin should already support this as it does scan the namespaces to check for custom enchantments.
Is there an example plugin I can download which will replicate this?

**Comment by RockinChaos** [comment]
Ah I see, okay perfect. This is exactly what I needed to know.
I will do some testing and update you here as I progress on this feature request.

Its been a while since I had added support for custom enchants so it does sound like some compatibility is missing from ItemJoin.

**Comment by ryantheleach** [comment]
```
  item_5:
    id: DIAMOND_SWORD
    lore:
    - '&8Soulbound'
    properties: 'Enchantments:[{id: "vane_enchantments:soulbound", lvl:1s}]'

```

For what it's worth, if it was possible to provide enchantments via properties, this is what I would expect.
