### ISSUE TITLE
Per Player Items

### ISSUE THREAD

**Issue by RockinChaos** [RockinChaos/ItemJoin#460]
Rosie Bot: Feature Request
Requested By: Explained#3173

[](https://cdn.discordapp.com/attachments/917101332756856832/917102170845896774/items.yml)Explained — 12/05/2021
@[DE/EN] TheRobLP Hello when I run the /kill command on myself, I don't get back my already modified pick, only the default one
[DE/EN] TheRobLP — 12/05/2021
Hey there. One second please
Explained — 12/05/2021
Sure
[DE/EN] TheRobLP — 12/05/2021
Okay, Im here for you now. Could you send your items.yml in here?
Explained — 12/05/2021
yes
```
# --{ =-=-=-=-=-=-=-=-=-= ItemJoin's Custom Item Configurations, by RockinChaos =-=-=-=-=-=-=-=-=-= }--
# See the tutorial page for a more in-depth explanation; https://github.com/RockinChaos/ItemJoin/wiki
# Join the discord for easy plugin support; https://discord.gg/D5FnJ7C
# 
# Modifying the Version will cause this file to break and regenerate.
items-Version: 8
items-Delay: 2
items-Overwrite: false
items-Spamming: false
items-RestrictCount: false
items:
  item_1:
    id: DIAMOND_PICKAXE
    slot: 0
    lore:
    - '&aEfficiency 10'
    - '&9Fortune 10'
    - '&cUnbreaking 10'
    inventory-left:
    - 'message: §6§l(!) §fSorry, but you can''t move your Pickaxe!'
    enchantment: UNBREAKING:10, EFFICIENCY:10, FORTUNE:10
    itemflags: UNBREAKABLE, HIDE-ATTRIBUTES, PLACEMENT, CANCEL-EQUIP, INVENTORY-MODIFY,
      DEATH-KEEP, SELF-DROPS, ITEM-CHANGABLE
    triggers: JOIN, RESPAWN
```
[DE/EN] TheRobLP — 12/05/2021
Wait.
Do you mean you want to modify the pickaxe AFTER you have gotten it? 
Explained — 12/05/2021
yes, i want the already modified pickaxe after death, not the default one
i mean, i applyed a speed enchant for example
[DE/EN] TheRobLP — 12/05/2021
Oooh. Well, such a feature doesn't exist right now within ItemJoin. What I could do for you is to escalate your ticket to RockinChaos as a feature request and he can tell you if he is able to add a feature for per-player items such as a new itemflag. 
Explained — 12/05/2021
Its okay
[DE/EN] TheRobLP — 12/05/2021
So, do you want me to escalate your ticket to the developer so he can look into a solution for your problem?
To be honest, I quite like the idea of modifiable items.
Explained — 12/05/2021
Yes!
Explained — 12/05/2021
Sounds great 😄
[DE/EN] TheRobLP — 12/05/2021
Alright, I will escalate your ticket. @Explained pinging you so you won't get confused. I am going to rename your ticket to ticket-f-per-player-items (the f means feature).
-escalate
🎟 Rosie
BOT
 — 12/05/2021
Escalated
This ticket has been escalated by a moderator and will be reviewed shortly.
[DE/EN] TheRobLP — 12/05/2021
-rename f-per-player-items
🎟 Rosie
BOT
 — 12/05/2021
Ticket renamed successfully!
[DE/EN] TheRobLP — 12/05/2021
@[EN] RockinChaos Hey there boss. We have a feature request here. This user would like to be able to modify his ItemJoin item after receiving it, and when the user dies he should receive his item back with all of the modifications he made AFTER he got the item. Is there any way you could see that being possible? Personally I really like the idea but I have no idea if that can work from a development perspective.
[EN] RockinChaos — 12/06/2021
Oof this might be a difficult feature to implement, I will look into this and update you once I have more information on this.
