### ISSUE TITLE
Disposable-fail-message is not working.

### ISSUE THREAD

**Issue by Thermors** [RockinChaos/ItemJoin#499]
## Disposable-fail-message is not working.

**The bug**
Disposable-fail-message is not displayed in the game chat, despite the fact that the flag "disposable" is set on item.

I wrote disposable conditions and fail message as in example on wiki:
disposable-conditions:
- '%luckperms_inherits_group_donate_1%:notequal:yes'
- '%luckperms_inherits_group_donate_2%:notequal:yes'
- '%luckperms_inherits_group_donate_3%:notequal:yes'
disposable-fail-message: '&cYou get to keep your item, lucky!'

**Expected behavior**
Dispayed message in the game chat: '&cYou get to keep your item, lucky!'

 - Resource Version and Build Number: [5.2.5-RELEASE-b850]
 - Server Version [Paper-1.18.2]

**Comment by RockinChaos** [comment]
Can you send me the exact item in question?
The following seems to work as intended and sends the fail message if any of the conditions are not met.

```
    itemflags: disposable
    interact:
    - 'say hi'
    disposable-conditions:
    - '%luckperms_inherits_group_donate_1%:notequal:yes'
    - '%luckperms_inherits_group_donate_2%:notequal:yes'
    - '%luckperms_inherits_group_donate_3%:notequal:yes'
    disposable-fail-message: '&cYou get to keep your item, lucky!'
```
