### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ImSmoch** [RockinChaos/ItemJoin#530]
How can I make the item change by left-clicking so that the text changes and the command to be executed changes as shown in the following images?

I used ItemJoin v5.2.5-RELEASE-b850

Spigot 1.8.8

![2023-04-01_10 31 25](https://user-images.githubusercontent.com/81275112/229303330-d9480b70-14f4-4c9b-8133-e7926a5ca3fb.png)

![2023-04-01_10 31 29](https://user-images.githubusercontent.com/81275112/229303336-a01138c2-dd9a-486c-923e-e3eb914f7306.png)

![2023-04-01_10 31 30](https://user-images.githubusercontent.com/81275112/229303347-dc069efe-12e3-4d08-a6bc-2df5a3b4b2bc.png)

**Comment by RockinChaos** [comment]
As per the wiki the swap-item command feature will do this.
Example; 
```
  example-1:
    id: DIAMOND_SWORD
    interact:
      - 'console: say command1'
      - 'console: say command2'
      - 'swap-item: example-2'
    enabled-worlds: world
  example-2:
    id: STONE_SWORD
    interact:
      - 'console: say command3'
      - 'console: say command4'
      - 'swap-item: example-1'
    enabled-worlds: world
```
