### ISSUE TITLE
Placeholders in lores

### ISSUE THREAD

**Issue by ArmanUppal** [RockinChaos/ItemJoin#546]
### Server Version

PaperSpigot 1.20

### Resource Version

ItemJoin v6.0.2

### Dump Information

n/a

### Describe The Problem

I heard that using this plugin you can out placeholders in lores. I wanted to make one for fortune on a pickaxe so everytime i get a higher fortune the placeholder also changes. How can I do this?

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [x] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Apologies for the late reply,

After a lot of looking around it looks like you would want the `Player` expansion from PlaceholderAPI and to use the placeholder `%player_item_in_hand_level_LOOT_BONUS_BLOCKS%`

The custom item would need to have the `dynamic` itemflag as well so it can update the lore's placeholder automagically.

An item may look like this;
```
  mining-item:
    id: DIAMOND_PICKAXE
    slot: 0
    lore:
      - '&aYou have a Level &c%player_item_in_hand_level_LOOT_BONUS_BLOCKS% &aPickaxe!'
    itemflags: dynamic
```
