### ISSUE TITLE
auto-remove

### ISSUE THREAD

**Issue by vuhgyxg** [RockinChaos/ItemJoin#558]
### Server Version

spigot 1.8

### Resource Version

itemjoin-6.0.2v

### Dump Information

https://pastebin.com/jjFkJgX2

### Describe The Problem

Hi can you help me, I use itemjoin compass with Chestcommands in my server, but when I teleport to world like pvp the compass stays in my inventory how can I remove it

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my help request is unique and another request does not exist.
- [X] I acknowledge this is not a bug report and is instead a help request.

**Comment by RockinChaos** [comment]
Have you tried using the `auto-remove` itemflag? That is what its designed for, I see you put it in the title but it doesn't seem to be on the item in ur pastebin so I am unsure if you tried it.

Keep in mind you also must define the `world-switch` trigger so auto-remove is allowed to function upon switching worlds.

It should look something like this;
```
items:
  compass-item:
    id: compass
    slot: 0
    name: '&aQuick Compass'
    interact:
      - 'console: cc open compass %player%'
    itemflags: auto-remove
    triggers: join, world-switch
    enabled-worlds: world
```
