### ISSUE TITLE
Clear-Items set to ITEMJOIN also clears Vanilla items, but only certain ones

### ISSUE THREAD

**Issue by czerk89** [RockinChaos/ItemJoin#585]
### Server Version

paper-1.20.4-454

### Resource Version

6.0.5-RELEASE-b928

### Dump Information

https://ci.craftationgaming.com/dump?id=ikacokadip

### Describe The Bug

I have the config file set to this:

```
Clear-Items:
  Type: ITEMJOIN
  Delay-Tick: 2
  Join: true
  Quit: true
  World-Switch: true
  Region-Enter: true
  Options: PROTECT, PROTECT_OP
  Blacklist: ''
```

But when I join a world, it clears vanilla items like swords and shields. It doesn't clear items like blocks. Or bones. I haven't tested every item it clears and doesn't clear. Even if I craft the item, like a shield, it still disappears.

### Expected Behavior

I would expect it to only clear itemjoin items. I even used `/data` to check the tags of vanilla items to see if anything was off.

### Steps To Reproduce

1. Set all `Clear-Items` values to `true`
2. Create an item join item like such:

```
  cartographer-item:
    id: FILLED_MAP
    slot: 0
    name: '&eMinimap'
    lore:
    - '&7Map updates as you move and'
    - '&7you can equip it as a shield!'
    itemflags: hide-flags, death-drops, self-drops, unbreakable, item-store, move-next
    enabled-worlds: ALL
```

3. Run the commands `/give bone 1` and `/give diamond_sword` in a survival world.
4. Join the world. You should not have 3 items in the hot bar--1 itemjoin and 2 vanilla.
5. Leave the world and come back. The sword will be gone. So you'll only have itemjoin item and bone.
6. Then run `/give diamond_sword` again so you have 3 items in the hot bar--1 itemjoin and 2 vanilla.
7. Change `Clear-Items` type from `ITEMJOIN` to `VANILLA`.
8. Leave the world and come back. Now ONLY the bone will be gone, but the diamond_sword will remain.

My expected behavior would be that with `ITEMJOIN`, only the map would be gone. And with `VANILLA`, both the sword and bone would be gone. Also, if you set `{id:DIAMOND_SWOTH}`, then the sword remain with ITEMJOIN, as you would expect. But I shouldn't have to blacklist a vanilla item. I didn't find anything in the [wiki](https://github.com/RockinChaos/ItemJoin/wiki/Config.yml#clear-items) about this behavior either. And no existing issue was found.

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.
