### ISSUE TITLE
Respawning after dying in a different world causes some items to appear that should not

### ISSUE THREAD

**Issue by czerk89** [RockinChaos/ItemJoin#589]
### Server Version

paper-1.20.4-454

### Resource Version

6.0.6-SNAPSHOT-b979

### Dump Information

https://ci.craftationgaming.com/dump?id=naximibono

### Describe The Bug

When I die (and only when I die), I'm respawned in the hub world with 2 items that I shouldn't have.

### Expected Behavior

I shouldn't spawn with any items since the hub world isn't listed in the `enabled-worlds`.

### Steps To Reproduce

1. Create a world as the hub world called "hub"
2. Create a second world called "world"
3. Set hub world as the spawn point
4. Create these three items:

```
  cartographer-item:
    id: FILLED_MAP
    map-id: 212
    slot: 1, Arbitrary
    name: '&eMinimap'
    lore:
    - '&7Map updates as you move and'
    - '&7you can equip it as a shield!'
    itemflags: hide-flags, death-drops, self-drops, unbreakable, item-store
    triggers: join, world-switch
    permission-node: itemjoin.map
    enabled-worlds: world
  teleport-item:
    id: CLOCK
    name: '&eTeleport Stone'
    slot: 35
    lore:
    - '&7Click to go to Hub!'
    interact:
    - 'delay: 1'
    - mvtp hub
    - 'message: &eSending you to the Hub!'
    inventory:
    - 'delay: 1'
    - mvtp hub
    - 'message: &eSending you to the Hub!'
    inventory-creative:
    - 'delay: 1'
    - mvtp hub
    - 'message: &eSending you to the Hub!'
    itemflags: inventory-modify, hide-flags, death-drops, self-drops, unbreakable, item-store
    triggers: join, world-switch
    permission-node: itemjoin.teleport
    enabled-worlds: world
  potion-item:
    id: GOLDEN_APPLE
    slot: 8
    count: 6
    name: '&c&nZomb of Power'
    lore:
    - '&7This is not any ordinary apple.'
    potion-effects: JUMP:8:60, NIGHT_VISION:2:60, GLOWING:6:60, REGENERATION:6:60, DAMAGE_RESISTANCE:6:60, HEAL:20:15, HEALTH_BOOST:6:15, INCREASE_DAMAGE:6:60, SLOW_FALLING:2:60, SPEED:3:60
    triggers: join, world-switch
    itemflags: inventory-modify, hide-flags, death-drops, self-drops, unbreakable, item-store, overwrite
    enabled-worlds: world
```

5. Run `/mvtp world`
6. When you enter the world, you should have 3 items.
7. Get a zombie to kill you.
8. When you spawn in hub, you'll still have `cartographer-item` and `teleport-item`. But you won't have the `  potion-item`. But "hub" isn't listed as an `enabled-worlds`, so the items shouldn't appear. Furthermore, why do only 2 items remain.

### Checklist

- [X] I am running latest version of this resource.
- [X] I have read the wiki to make sure it's not an issue with configuration.
- [ ] I ticked all of these boxes without actually reading them.
- [X] I have checked that my bug report is unique and a previous report does not exist.
