### ISSUE TITLE
Join command permission condition

### ISSUE THREAD

**Issue by FrancescoJacovo** [RockinChaos/ItemJoin#590]
### Describe The Feature

Adding a check for executing e command only if the player has a permission

### Expected Solution

commands:
  - 'itemjoin get <item> <player>'
  - 'first-join: say This is a command only executed once per world, per player.'
  - '[perm:have.this.command] first-join: say This is a command only executed once per world, per player.'

### Describe Alternatives Considered

Nothing more xd

### Checklist

- [X] I have read the wiki to make sure my request has not already been implemented.
- [X] I ticked all of these boxes without actually reading them.
- [X] I have checked that my feature request is unique and another request does not exist.

**Comment by RockinChaos** [comment]
After looking at this it's a bit vague on what you are looking for, but I just added in the latest snapshot support for command-permission conditions so hopefully this is what you are looking for;

* item command permissions
  * Every command action can have its own permission or set of permissions required to execute the command. In the example below I use `interact`, but this can be anything like `interact-right`, `interact-left`, `inventory`, `inventory-creative`, etc.
  * You can use a `!` symbol in front of the permission to invert the condition, making the permission strictly not required to execute the command. If they have that permission and it's not set to false then they will not be allowed to execute the command.
  * Example;
```
    interact:
    - 'console: eco give %player% 5000'
    interact-permission: 
    - '!itemjoin.group.owner'
    - 'itemjoin.group.newbies'
    interact-fail-message: '%prefix% &cfailed to execute the interact-right commands.'
```
