### ISSUE TITLE
FirstJoin Mode Custom Book cannot be given besides AuthMe

### ISSUE THREAD

**Issue by snakevil** [RockinChaos/ItemJoin#82]
Thanks for your brilliant work! It made me a custom GUIDE book could be used to show another custom menu. Perfect :)

However, when I tried to re-initialize my server, after the registration by AuthMe, **I'd got a fews kits by Essentials, but no expected custom book**.

Can you help me to solve that, please?

This is my server environment:

```
AuthMe (5.2-BETA3-b1134), BossShop (2.7.3), ChangeSkin (2.3.2), CoreProtect (2.13.2), Essentials (TeamCity), EssentialsAntiBuild (TeamCity), EssentialsChat (TeamCity), EssentialsProtect (TeamCity), EssentialsSpawn (TeamCity), ItemJoin (3.8), PermissionsEx (1.23.4), PlugMan (2.1.1), ProtocolLib (4.2.0), Vault (1.5.6-b49), WorldEdit (6.1.5;4651611)
```

And this is my `items.yml`:

```
items-Version: 5

Global-Settings:
  Prevention:
    prevent-pickups: false
    AllowOPBypass: false
    CreativeBypass: false
  Clear-On:
    clear-on-join: false
    clear-on-world-change: false
    clear-only-itemjoin-on-join: false
    clear-only-itemjoin-on-world-change: false
    AllowOPBypass: false
  First-Join:
    FirstJoin-Mode-Enabled: true
  Get-Items:
    ItemJoin-Specific-Items: true
    Global-Items: true
    Delay: 2

world-list:
  - world

world:
  items:
    bible:
      id: WRITTEN_BOOK
      slot: 5
      name: '&aAt Its Finest'
      author: '&bItemJoin'
      lore:
        - '&7'
        - '&7This magical book is given on join!'
      pages:
        - 'newpage: &bYou can get this book on join!'
        - 'newline: &aThis book also supports &ccolor codes!'
        - 'newline: &0'
        - 'newline: &cHow do custom books work?'
        - 'newline: &0'
        - 'newline: &0You can set an &cauthor&0'
        - 'newline: &0as shown in the items.yml'
        - 'newline: &0I set it to &bItemJoin.'
        - 'newline: &0'
        - 'newpage: &cHow do you create a new page?'
        - 'newline: &0'
        - 'newline: &0As displayed to the left in the items.yml'
        - 'newline: &0Use &bnewpage&0 and &cnewline&0 to create your pages.'
        - 'newline: &cnewpage &0will start the next page.'
        - 'newline: &cnewline &0will create a new line for that page.'
        - 'newpage: &bItemJoin &0by RockinChaos!'
        - ':endthebook:'
      commands:
      - 'menu'
      commands-action: LEFT_CLICK_AIR, LEFT_CLICK_BLOCK, PHYSICAL
      commands-cooldown: 1
      itemflags:
      - 'first-join'
      - 'death-drops'
      - 'self-drops'
      - 'respawn'
```
